
TYPE
	gES_typ : STRUCT
		DIR_MAN_ACTION_ENUM : ARRAY[0..6]OF STRING[32] := ['DIR_MAN_ACTION_NONE', 'DIR_MAN_ACTION_COPY_TO_USER', 'DIR_MAN_ACTION_COPY_TO_USB', 'DIR_MAN_ACTION_DELETE_USER', 'DIR_MAN_ACTION_DELETE_USB', 'DIR_MAN_ACTION_CREATE_DIR_USER', 'DIR_MAN_ACTION_CREATE_DIR_USB'];
		DIR_MAN_STATE_ENUM : ARRAY[0..11]OF STRING[32] := ['DIR_MAN_RESET', 'DIR_MAN_DIRMAKE_CMD', 'DIR_MAN_DIRMAKE_WAIT', 'DIR_MAN_DIRREAD_CMD', 'DIR_MAN_DIRREAD_WAIT', 'DIR_MAN_DIRREAD_USB_CMD', 'DIR_MAN_DIRREAD_USB_WAIT', 'DIR_MAN_DIRSANITIZE_CMD', 'DIR_MAN_DIRSANITIZE_WAIT', 'DIR_MAN_TRANSFER_CMD', 'DIR_MAN_TRANSFER_WAIT', 'DIR_MAN_DELAY'];
		TIME_STATE_ENUM : ARRAY[0..5]OF STRING[32] := ['TIME_RESET_C', 'TIME_CHECKPARREADY_W', 'TIME_IDLE_I', 'TIME_SET_C', 'TIME_SET_W', 'TIME_ERROR'];
		RECIPE_ID_ENUM : ARRAY[0..1]OF STRING[32] := ['RECIPE_ID_REM', 'RECIPE_ID_PAR'];
		MON_ENUM : ARRAY[0..10]OF STRING[32] := ['MON_SYSTEM_PAR_NOT_READY', 'MON_SYSTEM_HMI_STOP', 'MON_SAFETY_ESTOP', 'MON_RECIPE_REM_LOST_REM', 'MON_RECIPE_LOAD_BAD_REM', 'MON_RECIPE_LOAD_GOOD_REM', 'MON_RECIPE_GEN_ERR_REM', 'MON_RECIPE_REM_LOST_PAR', 'MON_RECIPE_LOAD_BAD_PAR', 'MON_RECIPE_LOAD_GOOD_PAR', 'MON_RECIPE_GEN_ERR_PAR'];
		PROCESS_ENUM : ARRAY[0..1]OF STRING[32] := ['PROCESS_MASTER', 'PROCESS_TEMP'];
		MASTER_EVAL_ENUM : ARRAY[0..8]OF STRING[32] := ['MASTER_EVAL_RESET', 'MASTER_EVAL_INIT', 'MASTER_EVAL_STOP_UNCONTROLLED', 'MASTER_EVAL_STOP_CONTROLLED', 'MASTER_EVAL_STOP_NORMAL', 'MASTER_EVAL_UNPAUSE', 'MASTER_EVAL_PAUSE', 'MASTER_EVAL_WAIT_BUFFER_EMPTY', 'MASTER_EVAL_START'];
		MASTER_CALL_ENUM : ARRAY[0..7]OF STRING[32] := ['MASTER_CALL_IDLE', 'MASTER_CALL_RESET', 'MASTER_CALL_STOP_UNCONTROLLED', 'MASTER_CALL_STOP_CONTROLLED', 'MASTER_CALL_STOP_NORMAL', 'MASTER_CALL_UNPAUSE', 'MASTER_CALL_PAUSE', 'MASTER_CALL_START'];
		DRIVER_INST_IN_ENUM : ARRAY[0..0]OF STRING[32] := ['DRIVER_INST_IN_0'];
		C_IN_ENUM : ARRAY[0..8]OF STRING[32] := ['C_IN_RESET', 'C_IN_CLEARCMD', 'C_IN_CLEARMON', 'C_IN_DEFAULTMON', 'C_IN_CLEARPAR', 'C_IN_DEFAULTPAR', 'C_IN_SAVEPAR', 'C_IN_FORCEENABLE', 'C_IN_FORCEDISABLE'];
		M_IN_ENUM : ARRAY[0..0]OF STRING[32] := ['M_IN_DI_ESTOP'];
		W_IN_ENUM : ARRAY[0..0]OF STRING[32] := ['W_IN_DI_ESTOP'];
		DRIVER_INST_DO_ENUM : ARRAY[0..0]OF STRING[32] := ['DRIVER_INST_DO_0'];
		C_DO_ENUM : ARRAY[0..9]OF STRING[32] := ['C_DO_RESET', 'C_DO_CLEARCMD', 'C_DO_CLEARMON', 'C_DO_CLEARPAR', 'C_DO_DEFAULTMON', 'C_DO_DEFAULTPAR', 'C_DO_SAVEPAR', 'C_DO_ERRORRESET', 'C_DO_DISABLEALL', 'C_DO_ENABLE'];
		M_DO_ENUM : ARRAY[0..0]OF STRING[32] := ['M_DO_ERROR'];
		W_DO_ENUM : ARRAY[0..0]OF STRING[32] := ['W_DO_NOERROR'];
		DRIVER_INST_AB_ENUM : ARRAY[0..11]OF STRING[32] := ['DRIVER_INST_AB_VX_0', 'DRIVER_INST_AB_VY_0', 'DRIVER_INST_AB_VZ_0', 'DRIVER_INST_AB_VT_0', 'DRIVER_INST_AB_VV_0', 'DRIVER_INST_AB_RX_0_0', 'DRIVER_INST_AB_RY_0_0', 'DRIVER_INST_AB_RZ_0_0', 'DRIVER_INST_AB_RT_0_0', 'DRIVER_INST_AB_RV_0_0', 'DRIVER_INST_AB_RP_0_0', 'DRIVER_INST_AB_RP_1_0'];
		C_AB_ENUM : ARRAY[0..21]OF STRING[32] := ['C_AB_RESET', 'C_AB_CLEARCMD', 'C_AB_CLEARMON', 'C_AB_DEFAULTMON', 'C_AB_CLEARPAR', 'C_AB_DEFAULTPAR', 'C_AB_SAVEPAR', 'C_AB_LOADPAR', 'C_AB_ERRORRESET', 'C_AB_HOME', 'C_AB_POWER', 'C_AB_UPDATE', 'C_AB_AUTOTUNE', 'C_AB_JOGPOSITIVE', 'C_AB_JOGNEGATIVE', 'C_AB_LIMITLOAD', 'C_AB_STOP', 'C_AB_MOVEABSOLUTE', 'C_AB_MOVEADDITIVE', 'C_AB_MOVEVELOCITY', 'C_AB_RELEASEBRAKE', 'C_AB_SIMULATE'];
		M_AB_ENUM : ARRAY[0..1]OF STRING[32] := ['M_AB_ERROR', 'M_AB_NOTPOWERON'];
		W_AB_ENUM : ARRAY[0..18]OF STRING[32] := ['W_AB_NOERROR', 'W_AB_COMMUNICATIONREADY', 'W_AB_READYTOPOWERON', 'W_AB_POWERON', 'W_AB_ISHOMED', 'W_AB_LIMITLOADACTIVE', 'W_AB_MOVEDONE', 'W_AB_UPDATEDONE', 'W_AB_AUTOTUNEDONE', 'W_AB_BRAKERELEASED', 'W_AB_COMMANDABORTED', 'W_AB_COMMANDBUSY', 'W_AB_INPOSITION', 'W_AB_INVELOCITY', 'W_AB_MOVEACTIVE', 'W_AB_STOPPED', 'W_AB_JOGGING', 'W_AB_JOGLIMITREACHED', 'W_AB_SIMULATION'];
		DRIVER_INST_CS_ENUM : ARRAY[0..9]OF STRING[32] := ['DRIVER_INST_CS_VX_0', 'DRIVER_INST_CS_VY_0', 'DRIVER_INST_CS_VZ_0', 'DRIVER_INST_CS_VT_0', 'DRIVER_INST_CS_VV_0', 'DRIVER_INST_CS_RX_0_0', 'DRIVER_INST_CS_RY_0_0', 'DRIVER_INST_CS_RZ_0_0', 'DRIVER_INST_CS_RT_0_0', 'DRIVER_INST_CS_RV_0_0'];
		C_CS_ENUM : ARRAY[0..13]OF STRING[32] := ['C_CS_RESET', 'C_CS_CLEARCMD', 'C_CS_CLEARMON', 'C_CS_DEFAULTMON', 'C_CS_CLEARPAR', 'C_CS_DEFAULTPAR', 'C_CS_SAVEPAR', 'C_CS_LOADPAR', 'C_CS_ERRORRESET', 'C_CS_MOVECYCLICPOSITION', 'C_CS_MOVECYCLICVELOCITY', 'C_CS_TORQUECONTROL', 'C_CS_TORQUEFEEDFORWARD', 'C_CS_UPDATE'];
		M_CS_ENUM : ARRAY[0..6]OF STRING[32] := ['M_CS_ERROR', 'M_CS_NOTMOVECYCLICPOSITIONACTIVE', 'M_CS_NOTMOVECYCLICVELOCITYACTIVE', 'M_CS_NOTTORQUECONTROLACTIVE', 'M_CS_NOTTORQUEFEEDFORWARDACTIVE', 'M_CS_TCAXISLIMITACTIVE', 'M_CS_NOTTCINTORQUE'];
		W_CS_ENUM : ARRAY[0..12]OF STRING[32] := ['W_CS_NOERROR', 'W_CS_COMMANDABORTED', 'W_CS_COMMANDBUSY', 'W_CS_UPDATEDONE', 'W_CS_MOVECYCLICPOSITIONACTIVE', 'W_CS_MOVECYCLICVELOCITYACTIVE', 'W_CS_TORQUECONTROLACTIVE', 'W_CS_TORQUEFEEDFORWARDACTIVE', 'W_CS_TCAXISLIMITACTIVE', 'W_CS_TCDATAINITIALIZED', 'W_CS_TCINTORQUE', 'W_CS_TCREADY', 'W_CS_AXISREADY'];
		DRIVER_INST_CN_ENUM : ARRAY[0..0]OF STRING[32] := ['DRIVER_INST_CN_0'];
		C_CN_ENUM : ARRAY[0..18]OF STRING[32] := ['C_CN_RESET', 'C_CN_CLEARCMD', 'C_CN_CLEARMON', 'C_CN_DEFAULTMON', 'C_CN_CLEARPAR', 'C_CN_DEFAULTPAR', 'C_CN_SAVEPAR', 'C_CN_LOADPAR', 'C_CN_ERRORRESET', 'C_CN_HOME', 'C_CN_POWER', 'C_CN_UPDATE', 'C_CN_MOVEPROGRAM', 'C_CN_INTERRUPT', 'C_CN_CONTINUE', 'C_CN_STOP', 'C_CN_JOG', 'C_CN_MOVEBLOCK', 'C_CN_SINGLESTEP'];
		M_CN_ENUM : ARRAY[0..2]OF STRING[32] := ['M_CN_ERROR', 'M_CN_NOTPOWERON', 'M_CN_NOTMOVEACTIVE'];
		W_CN_ENUM : ARRAY[0..14]OF STRING[32] := ['W_CN_NOERROR', 'W_CN_COMMUNICATIONREADY', 'W_CN_READYTOPOWERON', 'W_CN_POWERON', 'W_CN_ISHOMED', 'W_CN_WAITFORCONTINUE', 'W_CN_MOVEDONE', 'W_CN_UPDATEDONE', 'W_CN_MOVEINTERRUPTED', 'W_CN_COMMANDABORTED', 'W_CN_COMMANDBUSY', 'W_CN_INMOTION', 'W_CN_MOVEACTIVE', 'W_CN_STOPPED', 'W_CN_SINGLESTEPACTIVE'];
		DRIVER_INST_TR_ENUM : ARRAY[0..0]OF STRING[32] := ['DRIVER_INST_TR_0'];
		C_TR_ENUM : ARRAY[0..10]OF STRING[32] := ['C_TR_RESET', 'C_TR_CLEARCMD', 'C_TR_CLEARMON', 'C_TR_DEFAULTMON', 'C_TR_CLEARPAR', 'C_TR_DEFAULTPAR', 'C_TR_SAVEPAR', 'C_TR_LOADPAR', 'C_TR_ERRORRESET', 'C_TR_ENABLE', 'C_TR_RESYNC'];
		M_TR_ENUM : ARRAY[0..0]OF STRING[32] := ['M_TR_ERROR'];
		W_TR_ENUM : ARRAY[0..0]OF STRING[32] := ['W_TR_NOERROR'];
		DRIVER_INST_MR_ENUM : ARRAY[0..0]OF STRING[32] := ['DRIVER_INST_MR_0'];
		C_MR_ENUM : ARRAY[0..12]OF STRING[32] := ['C_MR_RESET', 'C_MR_CLEARCMD', 'C_MR_CLEARMON', 'C_MR_DEFAULTMON', 'C_MR_CLEARPAR', 'C_MR_DEFAULTPAR', 'C_MR_SAVEPAR', 'C_MR_LOADPAR', 'C_MR_ERRORRESET', 'C_MR_MBMOPEN', 'C_MR_MBMASTER', 'C_MR_MBMCLOSE', 'C_MR_MBMCMD'];
		M_MR_ENUM : ARRAY[0..0]OF STRING[32] := ['M_MR_ERROR'];
		W_MR_ENUM : ARRAY[0..4]OF STRING[32] := ['W_MR_NOERROR', 'W_MR_MBMOPEN', 'W_MR_MBMASTER', 'W_MR_MBMCLOSE', 'W_MR_MBMCMD'];
		DRIVER_INST_BX_ENUM : ARRAY[0..0]OF STRING[32] := ['DRIVER_INST_BX_0'];
		C_BX_ENUM : ARRAY[0..9]OF STRING[32] := ['C_BX_RESET', 'C_BX_CLEARCMD', 'C_BX_CLEARMON', 'C_BX_DEFAULTMON', 'C_BX_CLEARPAR', 'C_BX_DEFAULTPAR', 'C_BX_SAVEPAR', 'C_BX_LOADPAR', 'C_BX_ERRORRESET', 'C_BX_ENABLE'];
		M_BX_ENUM : ARRAY[0..0]OF STRING[32] := ['M_BX_ERROR'];
		W_BX_ENUM : ARRAY[0..1]OF STRING[32] := ['W_BX_NOERROR', 'W_BX_ACTIVE'];
	END_STRUCT;
END_TYPE

