
TYPE
	TC_TypeSelect_typ : 	STRUCT 
		Select : TC_TYPE_ENUM;
		VarSINT : SINT;
		VarUSINT : USINT;
		VarINT : INT;
		VarUINT : UINT;
		VarDINT : DINT;
		VarUDINT : UDINT;
		VarREAL : REAL;
		VarLREAL : LREAL;
		VarTIME : TIME;
		VarDT : DATE_AND_TIME;
		VarSTRING_ADR : UDINT;
		VarSTRING_LEN : UDINT;
		VarWSTRING_ADR : UDINT;
		VarWSTRING_LEN : UDINT;
	END_STRUCT;
	TC_TYPE_ENUM : 
		(
		TC_TYPE_INT,
		TC_TYPE_USINT,
		TC_TYPE_SINT,
		TC_TYPE_UINT,
		TC_TYPE_DINT,
		TC_TYPE_UDINT,
		TC_TYPE_REAL,
		TC_TYPE_LREAL,
		TC_TYPE_TIME,
		TC_TYPE_DT,
		TC_TYPE_STRING,
		TC_TYPE_WSTRING
		);
END_TYPE
